sudo: required

language: java
jdk: oraclejdk8

services:
 -docker

before_install:
 - docker build .

script:
- mvn clean package -DskipTests

after_success:
 - docker login -u $DOCKER_USER -p $DOCKER_PASS
 - export IMAGE_NAME=nj1892/demo
 - docker build -t $IMAGE_NAME:latest .
 - docker push $IMAGE_NAME

deploy:
 provider: elasticbeanstalk
 region: "us-west-1"
 app: "docker-java"
 env: "DockerJava-env"
 bucket_name: "elasticbeanstalk-us-west-1-707234857887"
 bucket_path: "docker-java"
 on:
  branch: master
 access_key_id: $AWS_ACCESS_KEY
 secret_access_key:
  secure: $AWS_SECRET_KEY